version: 2
registries:
  private-pypi:
    type: python-index
    url: "https://pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple/"
    username: pat
    password: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    registries: "*"
    labels:
      - "maintenance"
      - "dependencies"
    versioning-strategy: increase-if-necessary
    groups:
      doc-deps:
        patterns:
        - "*sphinx*"
        - "numpydoc"
        - "jupytext"
        - "ipykernel"
        - "enum-tools"
      dev-deps:
        patterns:
        - "pytest*"
        - "mypy"
        - "requests-mock"
        - "pre-commit"
      src-deps:
        patterns:
        - "ansys-openapi-common"
        - "ansys-grantami-serverapi-openapi"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
      - "dependencies"
    groups:
       actions:
          patterns:
            - "*"
