version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    private-pypi:
        type: pip-registry
        url: https://pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple/
        username: ${{ vars.PYANSYS_PYPI_PRIVATE_USER }}
        password: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
      - "dependencies"
    versioning-strategy: increase-if-necessary
    groups:
      doc-deps:
        patterns:
        - "*sphinx*"
        - "numpydoc"
        - "jupytext"
        - "ipykernel"
        - "enum-tools"
      dev-deps:
        patterns:
        - "pytest*"
        - "mypy"
        - "requests-mock"
        - "pre-commit"
      src-deps:
        patterns:
        - "ansys-openapi-common"
        - "ansys-grantami-serverapi-openapi"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
      - "dependencies"
    groups:
       actions:
          patterns:
            - "*"
